application: mejcrt
version: dev
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /authtest
  script: authtest.app
  secure: always
- url: /.*
  script: mejcrt.app
  secure: always
