application: mejcrt
version: dev
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(index(.*\.(html|htm))?)?$
  static_files: static/index.html
  upload: static/index.html
- url: /authtest
  script: authtest.app
  secure: always
- url: /api/.*
  script: mejcrt.app
  secure: always
- url: /
  static_dir: static/
